x-db-env: &db_env
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_NAME: ${DB_NAME}

x-rabbit-env: &rabbit_env
  RABBITMQ_HOST: ${RABBITMQ_HOST}
  RABBITMQ_PORT: ${RABBITMQ_PORT}
  RABBITMQ_USER: ${RABBITMQ_USER}
  RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
  RABBITMQ_VHOST: ${RABBITMQ_VHOST}

x-redis-env: &redis_env
  REDIS_HOST: ${REDIS_HOST}
  REDIS_PORT: ${REDIS_PORT}

services:

  db:
    image: postgres:15
    container_name: hotel_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    command:
      [
        "redis-server",
        "--appendonly", "yes",
        "--appendfsync", "everysec"
      ]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  migrations:
    build:
      context: .
      dockerfile: migrations/Dockerfile
    container_name: migrations
    depends_on:
      - db
    environment:
      <<: *db_env
      PYTHONPATH: /app/src:/app
    volumes:
      - ./src:/app/src
      - ./shared:/app/shared
      - ./migrations:/app/migrations
      - ./alembic.ini:/app/alembic.ini
    command: >
      alembic upgrade head
    restart: "no"

  frontend:
    build:
      context: ./frontend_ui
      dockerfile: Dockerfile
    container_name: frontend_ui
    ports:
      - "8080:80"
    restart: always

  router:
    build:
      context: .
      dockerfile: src/router/Dockerfile
    container_name: router
    restart: always
    environment:
      PREDICTION_URL: ${PREDICTION_URL}
      AUTH_URL: ${AUTH_URL}
      BOOKING_URL: ${BOOKING_URL}
      SCHEDULER_URL: ${SCHEDULER_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_HASH_ALGORITHM: ${JWT_HASH_ALGORITHM}
    ports:
      - "8001:8000"
    volumes:
      - ./shared:/shared

  prediction:
    build:
      context: .
      dockerfile: src/prediction/Dockerfile
    container_name: prediction
    restart: always
    depends_on:
      migrations:
        condition: service_completed_successfully
    ports:
      - "8002:8000"
    volumes:
      - ./shared:/shared
    environment:
      <<: *db_env

  auth:
    build:
      context: .
      dockerfile: src/auth/Dockerfile
    container_name: auth
    restart: always
    depends_on:
      redis:
        condition: service_started
      migrations:
        condition: service_completed_successfully
      db:
        condition: service_started
      rabbitmq:
        condition: service_started
    ports:
      - "8003:8002"
    volumes:
      - ./shared:/shared
    environment:
      <<:
        - *db_env
        - *rabbit_env
        - *redis_env
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_HASH_ALGORITHM: ${JWT_HASH_ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      REFRESH_TOKEN_EXPIRE_MINUTES: ${REFRESH_TOKEN_EXPIRE_MINUTES}
      PASSWORD_HASH_ALGORITHM: ${PASSWORD_HASH_ALGORITHM}

  auth_hotel_created_consumer:
    build:
      context: .
      dockerfile: ./src/auth/Dockerfile
    command: python -m auth.cmd.run_hotel_created_consumer
    environment:
      <<:
        - *db_env
        - *rabbit_env
        - *redis_env
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_HASH_ALGORITHM: ${JWT_HASH_ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      REFRESH_TOKEN_EXPIRE_MINUTES: ${REFRESH_TOKEN_EXPIRE_MINUTES}
      PASSWORD_HASH_ALGORITHM: ${PASSWORD_HASH_ALGORITHM}
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  booking:
    build:
      context: .
      dockerfile: src/booking/Dockerfile
    container_name: booking
    restart: always
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    ports:
      - "8004:8000"
    volumes:
      - ./shared:/shared
    environment:
      <<:
        - *db_env
        - *rabbit_env
      OUTBOX_PUBLISH_INTERVAL_SEC: 2
      OUTBOX_BATCH_SIZE: 100

  booking_outbox_publisher:
    build:
      context: .
      dockerfile: ./src/booking/Dockerfile
    command: python -m booking.cmd.run_outbox_publisher
    environment:
      <<:
        - *db_env
        - *rabbit_env
      OUTBOX_PUBLISH_INTERVAL_SEC: 2
      OUTBOX_BATCH_SIZE: 100
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy


  scheduler:
    build:
      context: .
      dockerfile: src/scheduler/Dockerfile
    container_name: scheduler
    restart: always
    depends_on:
      db:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    ports:
      - "8005:8000"
    volumes:
      - ./shared:/shared
    environment:
      <<: *db_env
      ROUTER_URL: ${ROUTER_URL}

  scripts:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    container_name: scripts
    depends_on:
      db:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./scripts:/app/scripts
      - ./shared:/app/shared
      - ./data_import:/app/data_import
    environment:
      <<: *db_env

volumes:
  pg_data:
  redis-data: